services:
  - type: web
    name: node-backend
    env: node
    plan: free
    rootDir: backend            
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-instance
          property: connectionString
      - key: PORT
        value: "6379"
